### ISSUE TITLE
Support for dynamicWidgets 

### ISSUE THREAD

**Issue by thinq-spz** [typesense/typesense-instantsearch-adapter#106]
## Description
TS adapter does not support dynamic widgets which are supposed to reduce network traffic.

## Steps to reproduce
Example from 
https://www.algolia.com/doc/api-reference/widgets/dynamic-facets/js/
Produces the following error:

TypesenseInstantsearchAdapter.js:41         
       Error: 404 - Could not find a facet field named `*` in the schema.
    at TypesenseInstantsearchAdapter1._validateTypesenseResult (TypesenseInstantsearchAdapter.js:81:13)
    at TypesenseInstantsearchAdapter.js:28:14
    at Array.map (<anonymous>)
    at TypesenseInstantsearchAdapter1._callee$ (TypesenseInstantsearchAdapter.js:27:58)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:25:9)

**Comment by jasonbosco** [comment]
We need to add support for this on the Typesense Server side first: #612

**Comment by pixelkoduje** [comment]
I see that instead of the `"*" error`, it shows the error 'Field `name` is not marked as a guy in the schema.'
I using `const data = useDynamicWidgets({
     guys: ['*']
   })` in docker version 0.25.0.rc9
It's not finished, do I need to do something else to make it work?
I'm using react-instantsearch-hooks-web

**Comment by jasonbosco** [comment]
This is now available. Here's how to use it: https://github.com/typesense/typesense-instantsearch-adapter/issues/150#issuecomment-1441201147
