### ISSUE TITLE
Adding widgets results in error

### ISSUE THREAD

**Issue by dianos** [typesense/typesense-instantsearch-adapter#174]
## Description
when adding widgets on the render event, I get an error on data refresh from the adapter.  when I avoid adding this widget the error does not appear:  `_Number_of_Network_(RJ-45)_Ports`

Error:
Uncaught (in promise) Error: 404 - Could not find a facet field named `_Number_of_Network_(RJ-45)_Ports,_Number_of_Total_Expansion_Bays,_Number_of_USB_2.0_Ports,_Thunderbolt,_Total_Number_of_Ports,_Wireless_LAN,attrib.lvl0,categories.lvl0` in the schema.
    at TypesenseInstantsearchAdapter._validateTypesenseResult (TypesenseInstantsearchAdapter.js:86:13)
    at TypesenseInstantsearchAdapter.js:26:14
    at Array.map (<anonymous>)
    at TypesenseInstantsearchAdapter._callee$ (TypesenseInstantsearchAdapter.js:25:58)
    at tryCatch (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)

widgets being added:

'_Battery_Capacity', '_Battery_Chemistry', '_Cable_Length', '_Application/Usage', '_Battery_Rechargeable', '_Battery_Size', '_Device_Supported', '_Color', '_Connector_on_Second_End', '_Connector_on_First_End', '_Cable_Type', '_Maximum_Output_Current', '_Maximum_Output_Power', '_Packaged_Quantity', '_Material', '_Total_Number_of_USB_Ports', '_Lock_Configuration_Type', '_TAA_Compliant', '_Connectivity_Technology', '_Form_Factor', '_Height', '_Network_(RJ-45)', '_Width', '_Adapter_Type', '_HDMI', '_Host_Interface', '_Product_Color', '_Number_of_USB_3.0_Ports', '_Aspect_Ratio', '_Display_Size_Supported', '_Product_Family', '_Product_Material', '_Widescreen', '_Connector_Type_on_First_End', '_Connector_Type_on_Second_End', '_DisplayPort', '_Input_Voltage', '_Connector_Plating', '_Locking_Combination', '_Microphone', '_Network_Technology', '_Number_of_2.5&quot;_Bays', '_Number_of_Devices_Supported', '_Number_of_HDMI_Outputs', '_Number_of_Network_(RJ-45)_Ports', '_Number_of_Total_Expansion_Bays', '_Number_of_USB_2.0_Ports', '_Thunderbolt', '_Total_Number_of_Ports', '_Wireless_LAN'

**Typesense Version**:  .25.34

**Comment by jasonbosco** [comment]
Could you share your collection's schema (the response of `GET /collections`?
