### ISSUE TITLE
Adapater + Nuxt + SSR doesn't not seem work nicely 

### ISSUE THREAD

**Issue by reinoldus** [typesense/typesense-instantsearch-adapter#43]
## Description

There seem to be issues with ssr and this adapter, I built this sandbox to show the problem: https://codesandbox.io/s/dazzling-lichterman-zlo9y?file=/pages/search.vue

It includes pretty much the code from the docs. 

## Steps to reproduce

1. Go to the sandbox homepage, click on search -> everything works
2. Reload the page on /search: You'll get the following error:

```
 ERROR  [params.facets].flat is not a function                        06:05:48

  at SearchRequestAdapter._buildSearchParameters (node_modules/typesense-instantsearch-adapter/lib/SearchRequestAdapter.js:166:35)
  at node_modules/typesense-instantsearch-adapter/lib/SearchRequestAdapter.js:203:32
  at Array.map (<anonymous>)
  at SearchRequestAdapter._callee$ (node_modules/typesense-instantsearch-adapter/lib/SearchRequestAdapter.js:202:55)
  at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
  at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
  at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
  at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
  at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
  at node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
  at new Promise (<anonymous>)
  at SearchRequestAdapter.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
  at SearchRequestAdapter.request (node_modules/typesense-instantsearch-adapter/lib/SearchRequestAdapter.js:218:25)
  at TypesenseInstantsearchAdapter._callee3$ (node_modules/typesense-instantsearch-adapter/lib/TypesenseInstantsearchAdapter.js:149:39)
  at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
  at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
```

In my own project the initial SSR state is loaded, but once I change any parameter the following happens:

```
{
  "searches": [
    {
      "query_by": "name,brand",
      "num_typos": 1,
      "sort_by": "",
      "highlight_full_fields": "name,brand",
      "collection": "public_products",
      "facet_by": "",
      "filter_by": "",
      "page": 1
    },
    {
      "query_by": "name,brand",
      "num_typos": 1,
      "sort_by": "",
      "highlight_full_fields": "name,brand",
      "collection": "public_products",
      "q": "water",
      "facet_by": "marketing_claims,category_functional,approved",
      "filter_by": "category_functional:=[Moisturizers] && approved:=[true]",
      "max_facet_values": 25,
      "page": 1
    },
    {
      "query_by": "name,brand",
      "num_typos": 1,
      "sort_by": "",
      "highlight_full_fields": "name,brand",
      "collection": "public_products",
      "q": "water",
      "facet_by": "approved",
      "filter_by": "category_functional:=[Moisturizers]",
      "max_facet_values": 25,
      "page": 1,
      "per_page": 1
    }
  ]
}
```

I get the following response:

```
{
  "results": [
    {
      "code": 400,
      "error": "Parameter `q` is required."
    },
    {
      "facet_counts": [
        {
          "counts": [

          ],
          "field_name": ".......",
          "stats": {}
        },
        {
          "counts": [
            {
              "count": 5,
              "highlighted": "...",
              "value": "..."
            }
          ],
          "field_name": "...........",
          "stats": {}
        },
        {
          "counts": [
            {
              "count": 5,
              "highlighted": "true",
              "value": "true"
            }
          ],
          "field_name": "....",
          "stats": {}
        }
      ],
      "found": 5,
      "hits": [
        {
          "document": {
            "brand": "....",
            "category_functional": [
              "...."
            ],
            "frequency": 0,
            "id": "19877",
            "ingredients_by_id": [
            ],
            "marketing_claims": [
              "...."
            ],
            "name": ".....", 
             [...]
          },
          "highlights": [
            {
              "field": "name",
              "matched_tokens": [
                "Water"
              ],
              "snippet": ".....",
              "value": "......"
            }
          ],
          "text_match": 16907875
        },
[...]
      ],
      "out_of": 35919,
      "page": 1,
      "request_params": {
        "collection_name": "public_products",
        "per_page": 1,
        "q": "water"
      },
      "search_time_ms": 1
    }
  ]
}
```

As if the q parameters wasn't applied properly. Unfortunately, I do not even get to this state with the sandbox, but maybe the issues are related 

## Metadata
Copied apikey etc. from the books example: https://books-search.typesense.org/

**Comment by reinoldus** [comment]
This might actually be a none issue. The problem with the sandbox was that it had node 10 installed, but [].flat is supported in node11+

This sandbox seems to work:
https://codesandbox.io/s/zen-wave-poe9t?file=/pages/search.vue

Also might be worth noting that this adapater does not work with IE because of the use of .flat:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

And the issue that I have locally does not occur in this setup so it must be somewhere in my code.

I will close the issue

**Comment by reinoldus** [comment]
event though it seems to be somewhere in my code, but if someone has a hint that would be greatly appreciated
